### ISSUE TITLE
'BlePairingEvent' does not name a type in /lairdbt510.h file 

### ISSUE THREAD

**Issue by Adam-Martineau** [particle-iot/beacon-scanner-library#10]
Error generated: 
lib/BeaconScanner/lairdbt510.h:188:38: 'BlePairingEvent' does not name a type

On line:
static void onPairingEvent(const BlePairingEvent& event);

**Comment by Adam-Martineau** [comment]
This issue was found running this:

```
#include "Particle.h"
#include "BeaconScanner.h"

SYSTEM_THREAD(ENABLED);

void setup() {
}

unsigned long scannedTime = 0;

void loop() {
    if (Particle.connected() && (millis() - scannedTime) > 10000) {
        scannedTime = millis();
        Scanner.scanAndPublish(5, SCAN_IBEACON, "test", PRIVATE);
    }
}
```

**Comment by AMarquis1** [comment]
issue has been fixed: https://github.com/particle-iot/beacon-scanner-library/issues/8#issue-938422564

**Comment by ma-lemire** [comment]
Yooo, je l'avais déjà faite fix par le dude lundi. Comme j'ai dit sur le groupe FB, il faut le git c'one et non le particle install. Le fix n'est pas rendu sur le shit de particle. Le problème c'est que la lib est target sur > 3.0.0.
