### ISSUE TITLE
Library doesn't compile : identifier BlePairingEvent is not defined in lairdBt510.h

### ISSUE THREAD

**Issue by ma-lemire** [particle-iot/beacon-scanner-library#8]
Hi,

Trying to use your lib and in lairdBt510.h, you have a undefined identifier line 194 : static void onPairingEvent(const BlePairingEvent& event);

<img width="1440" alt="Screen Shot 2021-07-06 at 22 36 58" src="https://user-images.githubusercontent.com/31415349/124691964-b48edc00-deaa-11eb-999e-563038195310.png">

My system : 
MacOS : Big Sur (v 11.4)
MacBook Air (M1, 2020)

Particle Argon : DeviceOS 2.1.0

**Comment by mgolu** [comment]
Ah yes, the Laird device uses features only available in DeviceOS 3.0 or above. I just added #defines to exclude the Laird device when compiling with DeviceOS < 3.0.0, so your compilation should work now.

**Comment by ma-lemire** [comment]
@mgolu Works very well thx for the fix ! Have a nice evening ! :D
