### ISSUE TITLE
beacon.newly_scanned doesn't seems to work

### ISSUE THREAD

**Issue by ma-lemire** [particle-iot/beacon-scanner-library#9]
Question for you : the bool newly_scanned is very usefull for me, but it doesn't seems to work.
Can you help me ?

<img width="951" alt="Screen Shot 2021-07-07 at 00 47 15" src="https://user-images.githubusercontent.com/31415349/124701917-6800cc00-debd-11eb-8d49-6fe35b280e0f.png">

Same configuration :

MacOS : Big Sur 

Particle Argon : DeviceOS : 2.1.0

thx again,

Marc

**Comment by mgolu** [comment]
There is no difference between a newly scanned device and a device that entered the area. if `type` is `NEW`, then `newly_scanned` will always be the same value.
